#application.yml
server:
  port: 8088

spring:

    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/admin
        username: root
        password: chen
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    mybatis:
      mapperLocations: classpath:mapper/*Dao.xml
      typeAliasesPackage: com.miaoqu.entity

#    mapper:
#       mappers :
#       not-empty : false
#       identity : MYSQL
#

